<?php
namespace ShoppingFeed\Sdk\Test\Api\Order;

use ShoppingFeed\Sdk\Api;
use ShoppingFeed\Sdk\Order;

class OperationBatchCollectionMock extends Api\Order\OperationBatchCollection
{
    /**
     * Change accessibility for test
     *
     * @param array $criteria
     *
     * @return Api\Task\BatchResource[]
     * @throws Order\Exception\BatchNotFoundException
     */
    public function findBatchs(array $criteria = [])
    {
        return parent::findBatchs($criteria); // TODO: Change the autogenerated stub
    }
}
