<?php
namespace ShoppingFeed\Sdk\Test\Api\Order;

use ShoppingFeed\Sdk\Api\Order\OrderTicketCollection;

class OrderTicketCollectionMock extends OrderTicketCollection
{
    /**
     * Change accessibility for test
     *
     * @param array $criteria
     *
     * @return \ShoppingFeed\Sdk\Api\Task\TicketResource[]
     * @throws \ShoppingFeed\Sdk\Order\Exception\TicketNotFoundException
     */
    public function findTickets(array $criteria = [])
    {
        return parent::findTickets($criteria); // TODO: Change the autogenerated stub
    }
}
