<?php

namespace ShoppingFeed\Sdk\Api\Order;

class OrderOperationResult
{
    /** @var OrderOperationBatch[] $batches  */
    private array $batches;

    public function __construct(array $resources = [])
    {
        $this->setBatches($resources);
    }

    /**
     * Get the iterator for all tickets generated by the operation
     *
     * @return \ShoppingFeed\Sdk\Api\Task\TicketResource[]|\Traversable
     */
    public function getTickets()
    {
        foreach ($this->batches as $batch) {
            foreach ($batch->getResponse()->getTickets() as $ticket) {
                yield $ticket;
            }
        }
    }

    /**
     * @return string[] The list of ticket batch ids generated by the operation
     */
    public function getBatchIds()
    {
        $batchIds = [];

        foreach ($this->batches as $batch) {
            $batchIds[] = $batch->getResponse()->getBatchId();
        }

        return $batchIds;
    }

    /**
     * Wait for all tickets to be processed.
     *
     * @param ?int $timeout Seconds to wait for each batch until stop
     * @param int $sleepSecs Seconds to wait between to calls
     *
     * @return $this                      The current instance
     */
    public function wait($timeout = null, $sleepSecs = 1)
    {
        foreach ($this->batches as $batch) {
            $batch->getResponse()->wait($timeout, $sleepSecs);
        }

        return $this;
    }

    /**
     * @param \ShoppingFeed\Sdk\Hal\HalResource[] $resources
     */
    private function setBatches(array $resources): void
    {
        $this->batches = [];

        foreach ($resources as $resource) {
            $this->batches[] = new OrderOperationBatch($resource);
        }
    }

    /**
     * @return OrderOperationBatch[]
     */
    public function getBatches(): array
    {
        return $this->batches;
    }
}
