<?php

namespace ShoppingFeed\Sdk\Api\Order;

use ShoppingFeed\Sdk\Api\Task;
use ShoppingFeed\Sdk\Exception\RuntimeException;
use ShoppingFeed\Sdk\Hal\HalLink;
use ShoppingFeed\Sdk\Hal\HalResource;

class OrderOperationResponse
{
    private string $batchId;

    private Task\TicketDomain $ticketDomain;

    /**
     * @var array{int, array{
     *      id: int|null,
     *      channelName: string|null,
     *      reference: string|null,
     *      state: string,
     *      message: string
     *  }} $report
     */
    private array $report;

    public function __construct(HalResource $resource)
    {
        $this->batchId = $resource->getProperty('id');
        $this->report  = $resource->getProperty('report');
        $link          = $resource->getLink('ticket');

        if ($link instanceof HalLink) {
            $this->ticketDomain = new Task\TicketDomain($link);
        } else {
            throw new RuntimeException('Ticket link is missing from the OrderOperationResponse resource.');
        }
    }

    public function getBatchId(): string
    {
        return $this->batchId;
    }

    /**
     * Get the iterator for all tickets generated by the operation
     *
     * @return Task\TicketResource[]
     */
    public function getTickets(): iterable
    {
        foreach ($this->ticketDomain->getByBatch($this->batchId) as $ticket) {
            yield $ticket;
        }
    }

    /**
     * Wait for all tickets to be processed.
     *
     * $timeout Seconds to wait for each batch until stop
     * $sleepSecs Seconds to wait between to calls
     *
     * @return $this The current instance
     */
    public function wait(?int $timeout = null, int $sleepSecs = 1): self
    {
        $this->ticketDomain->getByBatch($this->batchId)->wait($timeout, $sleepSecs);

        return $this;
    }

    /**
     * @return array{int, array{
     *      id: int|null,
     *      channelName: string|null,
     *      reference: string|null,
     *      state: string,
     *      message: string
     *  }}
     */
    public function getReport(): array
    {
        return $this->report;
    }
}
